XC_PROJECT = File.absolute_path('../WebDriverAgent.xcodeproj')
RETRIES = 3

lane :test do
  test_run_block = lambda do |testrun_info|
    failed_test_count = testrun_info[:failed].size

    if failed_test_count > 0
      UI.important("Failed tests count: #{failed_test_count}")

      try_attempt = testrun_info[:try_count]
      if try_attempt < RETRIES
        UI.header("Re-running failing tests (attempt #{try_attempt} of #{RETRIES})")
        reset_simulator_contents
      end
    end
  end

  # https://docs.fastlane.tools/actions/scan/
  result = multi_scan(
    project: XC_PROJECT,
    try_count: RETRIES,
    fail_build: false,
    scheme: ENV['SCHEME'],
    sdk: ENV['SDK'],
    destination: ENV['DEST'],
    testrun_completed_block: test_run_block
  )
  unless result[:failed_testcount].zero?
    UI.message("There are #{result[:failed_testcount]} legitimate failing tests")
  end
end

desc "Debug build"
lane :UPDATE_PROJECT do
    update_app_identifier(
        xcodeproj: "WebDriverAgent.xcodeproj",
        app_identifier: "ch.mobiliar.WebDriverAgentLib",
        plist_path: "WebDriverAgentLib/Info.plist"
    )
    update_app_identifier(
        xcodeproj: "WebDriverAgent.xcodeproj",
        app_identifier: "ch.mobiliar.WebDriverAgentRunner",
        plist_path: "WebDriverAgentRunner/Info.plist"
    )
    update_app_identifier(
        xcodeproj: "WebDriverAgent.xcodeproj",
        app_identifier: "ch.mobiliar.IntegrationApp",
        plist_path: "WebDriverAgentTests/IntegrationApp/Info.plist"
    )
    enable_automatic_code_signing(
        team_id: "VXMWK5649M",
        code_sign_identity: "iPhone Developer"
    )
    #xcodebuild(
    #  archive: false,
    #  scheme: "WebDriverAgentRunner"
    #)
    #xcodebuild(
    #    archive: false,
    #    scheme: "IntegrationApp"
    #)
end
