export {englishTranslation};

const englishTranslation = {
    networkNotAvailableToInit: 'Network not available. The app can not be initialised.',
    networkNotAvailableToSelectPartner: 'Network not available to select this partner.',
    userHaveToLogin: 'You have to login first. The app can not be used without authentication.',
    waitingForInitialised: 'The app is being initialised. Please wait a moment...',
    errorWhenInitialised: 'The app could not be initialised successfully. Please close the app and try again later',
    favorites: 'Favorites',
    recent: 'Recent',
    partner: 'Partner',
    removePartner: 'Remove this partner from the device',
    markedPartners: 'Marked partners from B2E Portal',
    locallySavedPartners: 'Locally saved partners',
    emptyFavoritesTitle: 'Use Favorites from the B2E-Portal',
    emptyFavoritesContent:
        'All Partner marked as "Favorites" (Star) in the B2E-Portal will appear here, so you don\'t have to search them manually every time. Go and mark your most important customers as favorite to improve your efficiency!',
    basicData: 'Basic Data',
    telephoneNumber: 'Telephone number',
    mobileNumber: 'Mobile number',
    businessNumber: 'Business number',
    email: 'E-mail',
    address: 'Address',
    profession: 'Profession',
    customerPortal: 'Customer Portal',
    noMobiliarLogin: 'has no login',
    partnerRoles: 'Partner Roles',
    bankAccount: 'Bank account',
    partnerRelations: 'Partner Relations',
    active: 'active',
    activePascalCase: 'Active',
    roles: 'Roles',
    role: 'Role',
    terminated: 'Terminated',
    hasContracts: 'Has contracts',
    inactive: 'Inactive',
    contracts: 'Contracts',
    offers: 'Offers',
    documents: 'Documents',
    claims: 'Claims',
    claimADamage: 'Register a claim',
    pending: 'Pending',
    finished: 'Finished',
    showAllClaims: 'Show all claims',
    addPartner: 'Add partner',
    loginToContinue: 'Please login to continue.',
    networkNotAvailableForDownloadingData:
        'Network not available for downloading necessary data. Please try again later.',
    searchPartner: 'Search Partner',
    searchCriteria: 'Search Criteria',
    numberType: 'Number Type',
    partnerNumber: 'Partner Number',
    contractNumber: 'Contract Number',
    number: 'Number',
    invalidText: 'Invalid Text',
    emptyPartnerNumber: 'Enter a Partner Number to search for',
    invalidPartnerNumber: 'Invalid Partner Number',
    emptyContractNumber: 'Enter a Contract Number to search for',
    invalidContractNumber: 'Invalid Contract Number',
    invalidZipPlace: 'Enter a Zip Place to search for',
    invalidLastNameCompany: 'Enter a Last Name or a name of Company to search for',
    lastName: 'Last name/Company',
    firstName: 'First Name/Company',
    zipPlace: 'Zip Place',
    street: 'Street',
    noPartnerMatchWithSearchCondition: 'No Partners match your search',
    search: 'Search',
    loadingData: 'Loading data',
    errorWhenLoadPartnerBasicData: 'An unexpected errorIcon ocurred. Please try again later to load the partner.',
    singleOffer: '1 offer',
    manyOffers: '{{count}} offers',
    requireNetworkForDownload: 'You have to be online in order to download a document.',
    downloadDocumentError: 'The document could not be downloaded for unexpected reasons. Please try again later.',
    downloadingContractDocument: 'Downloading contract document. Please wait a moment...',
    noContract: 'No contracts',
    noOffer: 'No Offers',
    partnerDoesNotHaveContractYet: 'This partner does not have any contracts',
    partnerDoesNotHaveOfferYet:
        'This partner does not have any offers. You can create offers in the B2E-Portal. They will be displayed here.',
    callBack: 'Call Back',
    showAllCallBackTasks: 'Show all call back tasks',
    callBackTaskDetails: 'Call Back Task Details',
    description: 'Description',
    dueDate: 'Due date',
    created: 'Created',
    creator: 'Creator',
    completeLater: 'Complete later',
    complete: 'Complete',
    phone: 'Phone',
    tasks: 'Tasks',
    emptyTaskListTitle: 'Call Back Tasks from B2E-Portal',
    emptyTaskListDescription: 'In the B2E-Portal call back tasks can be created. They will be displayed here.',
    cannotCompleteTask:
        'An errorIcon occurred while trying to complete the task. Please try again later or contact the service desk.',
    document: 'document',
    downloadingPartnerDocument: 'Downloading partner document. Please wait a moment...',
    partnerDoesNotHaveAnyRelations: 'This partner does not have any partner relations.',
    noPartnerRelations: 'No partner relations',
    unableToLoadInformation: 'Unable to load information',
    unableToLoadInformationMessage:
        '"The app is not able to load the partner data. Select ""Synchronize"" to try again."',
    cancel: 'Cancel',
    switch: 'Switch',
    switchToRelatedPartner: 'Switch to related partner',
    switchToRelatedPartnerDescription: 'You can get back to the current partner via the home screen.',
    settings: 'Settings',
    configuration: 'Configuration',
    languageSelection: 'Language',
    keepDownloadedPartnersOnDevice: 'Keep downloaded partners on device',
    cleaningExpiredPartner: 'Cleaning 1 expired downloaded partner',
    cleaningExpiredPartners: 'Cleaning {{count}} expired downloaded partners',
    logout: 'Log out',
    startPhoneCall: 'Start a phone call',
    noNumberAvailable: 'No number available.',
    noEmailAvailable: 'No email address available.',
    noLocationAvailable: 'No location available.',
    place: 'Place',
    event: 'Event',
    noClaim: 'No Claim',
    noClaimMessage: 'This partner does not have any claims.',
    errorLoadingClaimResponsibleEmployee:
        'The information about the responsible employee can not be displayed at the moment',
    errorLoadingClaimLocation: 'The information about the location can not be displayed at the moment',
    errorLoadingPayment: 'The payment information cannot be displayed at the moment.',
    responsibleEmployee: 'Responsible employee',
    manyClaims: '{{count}} pending claims',
    singleClaim: '1 pending claim',
    manyDocuments: '{{count}} documents',
    singleDocument: '1 document',
    synchronizationIncomplete: 'Synchronization incomplete',
    synchronizationIncompleteMessage:
        'The app is not able to successfully synchronize all data. You can still work with all previously visited partners, although their data might be outdated.',
    outdatedInformation: 'Outdated information',
    outdatedInformationMessage:
        'The app is not able to load all the partner data. The data below was last updated on {{time}}',
    noDocuments: 'No documents',
    noDocumentsMessage:
        'This partner does not have any documents. You can scan and add new documents belonging to this partner such as official files, termination letters, power of attorney etc..',
    CRAIsNotAvailable: 'The Claim App (Claim Registration App) has not been installed',
    CRAIsNotAvailableMessage:
        'If you install the Claim App (Claim Registration App), you can directly register new claim cases for this partner!',
    scanbotSDKLicenseExpired: 'Your license have expired',
    scanbotSDKLicense: 'ScanBot License',
    documentPreview: 'Document preview',
    documentName: 'Document name',
    documentCategories: 'Document category and type',
    discardDocumentTitle: 'Discard this document?',
    discardDocumentMessage: 'You are about to discard the current document.',
    discard: 'Discard',
    keep: 'Keep',
    loadingImage: 'Loading images...',
    scanningDocument: 'Scanning document. Please wait a moment...',
    add: 'Add',
    categoryMissing: 'Category missing',
    categoryMissingMessage: 'Please categorize the document, so it can be found more easily later.',
    documentNameMissing: 'Document name missing',
    documentNameMissingMessage: 'Please update the document name',
    save: 'Save',
    addDocument: 'Add Document',
    done: 'Done',
    savingDocument: 'Saving document. Please wait a moment...',
    saveDocumentTitle: 'Save document',
    saveDocumentFail: 'An unexpected errorIcon occurred. Please try again later.',
    deleteThisPageTitle: 'Delete this page?',
    deleteThisPageMessage: 'You are about to delete the current scanned page.',
    uploadingMessage: 'Please wait while your new partner documents are being uploaded.',
    uploaded: 'Uploaded',
    failed: 'Failed',
    of: 'of',
    networkNotAvailableForUploadPartnerDocument:
        'In order to upload a document, you need a network connection. The scanned document is stored on your device. Try to upload it later when having a network connection by selecting the refresh button in the header.',
    uploadDocumentFailed: 'Upload failed',
    uploadDocumentFailedMessage:
        'The app is not able to successfully synchronize all data. You can still work with all previously visited partners, although their data it might be outdated.',
    uploadDocumentTitle: 'Uploading documents',
    delete: 'Delete',
    documentType: 'Document type',
    foreignContracts: 'Foreign Contracts',
    foreignContract: 'Foreign Contract',
    insuranceType: 'Insurance type',
    insuranceProvider: 'Insurance provider',
    expirationDate: 'Expiration date',
    additionalAttributes: 'Additional attributes',
    objectRisk: 'Object / Risk',
    annualPremium: 'Annual premium (CHF)',
    policeNumber: 'Policy number',
    remarks: 'Remarks',
    expirationDateHintTitle: 'Sales Opportunity',
    expirationDateHintDescription:
        'Setting the expiration date will automatically trigger a sales opportunity within the Sales Portal (VP).',
    addForeignContract: 'Add Foreign Contract',
    incompleteForeignContractTitle: 'Incomplete foreign contract',
    incompleteForeignContractContent:
        'Please fill out the incomplete fields, that the foreign contract can be submitted.',
    incompletePartnerDocumentTitle: 'Incomplete partner document',
    incompletePartnerDocumentContent:
        'Please fill out the incomplete fields, that the partner document can be submitted.',
    showAllContracts: 'Show all Contracts',
    foreignContractDetails: 'Foreign Contract Details',
    documentPascalCase: 'Document',
    uploadingForeignContractMessage: 'Please wait while your new foreign contracts are being uploaded.',
    invalidInsuranceProviderTitle: 'Insurance provider missing',
    invalidInsuranceProviderMessage: "Please indicate the 'Insurance provider'.",
    tooManySearchResultTitle: 'Too many search results',
    tooManySearchResultMessage:
        "Please refine your search if you can't find the right one among the partners shown below.",
    claimNumber: 'Claim Number',
    phoneNumber: 'Phone number',
    vehicleRegistrationNumber: 'Vehicle registration number',
    invalidVehicleRegistrationNumber: "Canton can  not be determined. Please enter a valid 2-letter code, f.i. 'BE'",
    attachments: 'Attachments',
    foreignContractsCamelCaseMany: '{{count}} foreign contracts',
    foreignContractsCamelCaseSingle: '1 foreign contract',
    toUpload: '{{count}} to upload',
    myMobiliar: 'MyMobiliar',
    responsibleAgent: 'Responsible agent (MBA)',
    unmarkAsFavorite: 'Unmark as favorite',
    markAsFavorite: 'Mark as favorite',
    synchronizePartnerData: 'Synchronize partner data',
    downloadAllDocuments: 'Download all documents',
    createNewTask: 'Create new task',
    unmarkPartnerAsFavoriteConfirmTitle: 'Unmark {{partnerName}} as favorite',
    unmarkPartnerAsFavoriteConfirmMessage:
        'Unmarking as favorite will make this partner disappear from this list as well as the favorite list in the B2E Portal.',
    unmark: 'Unmark',
    partnerActions: 'Partner actions',
    downloadingAllDocuments: 'Downloading all documents...',
    downloadedCount: 'Downloaded: {{countStatus}} of {{total}}',
    allDownloadedDocuments: 'All documents have been downloaded',
    noMoreDocumentsToDownload: 'There are no more documents to download',
    errorWhileDownloading: 'Error while downloading',
    failedDownloadCount: 'Failed: {{countStatus}} of {{total}} documents',
    failedDownloadDocumentTitle: 'Download all documents failed',
    failedMessageOnNotificationModal:
        'The app was not able to finish the action. Make sure that you have a stable connection while downloading. Click to try again.',
    retry: 'Retry',
    quickSearch: 'Quick search',
    partnerSearch: 'Partner search',
    newFreeTextTask: 'New free text task',
    subject: 'Subject',
    responsible: 'Responsible',
    startDate: 'Start date',
    comment: 'Comment',
    forwardWhenHandingOverCase: 'Forward when handing over case',
    create: 'Create',
    discardFreeTextTaskTitle: 'Discard this task?',
    discardFreeTextTaskMessage: 'You are about to discard the current task.',
    incompleteFreeTextTaskTitle: 'Missing subject field',
    incompleteFreeTextTaskContent: 'Please fill out the incomplete fields, that the task can be created.',
    creatingFreeTextTask: 'Creating free text task',
    responsibleCommunicationsActionHeader: 'MBA <<{{agentName}}>> Actions',
    responsiblePhoneCallAction: 'Call:{{phone}}',
    responsibleEmailAction: 'Email:{{email}}',
    myMobiliarActions: 'MyMobiliar Actions',
    generateNewActivationCode: 'Generate New Activation Code',
    generateActivationCode: 'Generate Activation Code',
    displayActivationCode: 'Display Activation Code',
    yourPersonalActivationCode: 'Your personal activation code',
    'validUntil.singular': 'Valid until: {{expiryDate}} ({{dayLeft}} day)',
    'validUntil.plural': 'Valid until: {{expiryDate}} ({{dayLeft}} days)',
    partnerIdentification: 'Partner Identification',
    pNumber: 'P-Number',
    contactEmail: 'Contact E-mail',
    contactMobileNumber: 'Contact Mobile number',
    partnerIdentificationConfirmMessage: 'Please confirm, that you have clearly identified this partner',
    confirm: 'Confirm',
    generatingActivationCode: 'Generating activation code. Please wait a moment...',
    cannotGenerateActivationCode: 'Cannot generate activation code. Please try again later.',
    courseOfEvents: 'Course of events',
    damageDate: 'Damage date',
    responsibleForClaim: 'Responsible for claim',
    responsibleForPartialClaim: 'Responsible for partial claim',
    partialClaimNumber: 'Partial claim number',
    status: 'Status',
    furtherPartialClaims: 'Further partial claims',
    hidePartialClaims: 'Hide partial claims',
    claimDetails: 'Claim overview',
    errorLoadingDamageDate: 'The information about the damage date can not be displayed at the moment',
    errorLoadingCourseOfEvents: 'The information about the course of events can not be displayed at the moment',
    errorLoadingCoverage: 'The information about the coverage can not be displayed at the moment',
    yes: 'Yes',
    no: 'No',
    missingClaimsTitle: 'Missing claims',
    missingClaimsDescription:
        'Unfortunately, claims that were recorded before mid-April 2017 cannot be displayed at the moment.',
    payments: 'Payments',
    compensation: 'Compensation',
    netCosts: 'Net costs',
    notifications: 'Notifications',
    partnersWithError: 'Partners with errors',
    partnersWithBackgroundTasks: 'Partners with background tasks',
    connectionError: 'Connection Error',
    requireInternetForAction: 'You need an internet connection to start this action.',
    actionDownloadAllTitle: 'Action Download all documents',
    actionIsRunning: 'This action is already running. Please wait until it is finished.',
    synchronizingPartnerData: 'Synchronizing partner data...',
    pleaseWait: 'Please wait a moment...',
    synchronizationFailed: 'Synchronization failed',
    actionSynchronizationTitle: 'Action Synchronize partner data',
    actionMarkAsFavorite: 'Action Mark as favorite',
    actionUnnmarkAsFavorite: 'Action Unmark as favorite',
    actionCreateFreeTextTaskTitle: 'Action Create free text task',
    actionScanDocumentTitle: 'Action Scan document',
    actionScanForeignContractTitle: 'Action Scan foreign contract',
    otherActionIsRunning: 'Other action is running. Please wait until it is finished.',
    coverageUnknown: 'Coverage unknown',
    uploadingDocuments: 'Uploading document(s)...'
};
