export {frenchTranslation};
const frenchTranslation = {
    networkNotAvailableToInit: 'Vous n’avez aucune connexion réseau. L’app ne peut pas être configurée.',
    networkNotAvailableToSelectPartner:
        'Vous ne pouvez pas charger ce partenaire car vous n’avez aucune connexion réseau.',
    userHaveToLogin: 'Veuillez d’abord vous connecter, sans quoi vous ne pourrez pas utiliser l’app.',
    waitingForInitialised: 'L’app est en cours de configuration. Veuillez patienter...',
    errorWhenInitialised: 'L’app n’a pas pu être configurée. Veuillez fermer l’app et réessayer plus tard.',
    favorites: 'Favoris',
    recent: 'Récent',
    partner: 'Partenaires',
    removePartner: 'Supprimer ce partenaire de l’appareil',
    markedPartners: 'Partenaires marqués du portail B2E',
    locallySavedPartners: 'Partenaires sauvés localement',
    emptyFavoritesTitle: 'Utilisez vos favoris du portail B2E.',
    emptyFavoritesContent:
        'Tous les partenaires que vous ajoutez à vos «favoris» (étoile) sur le portail B2E apparaissent ici et ne doivent pas être recherchés manuellement à chaque fois. Ajoutez vos clients les plus importants à vos favoris sur le portail B2E pour accroître votre efficacité!',
    basicData: 'Données de base',
    telephoneNumber: 'Téléphone privé',
    mobileNumber: 'Téléphone portable',
    businessNumber: 'Téléphone professionnel',
    email: 'E-mail',
    address: 'Adresse',
    profession: 'Profession',
    customerPortal: 'Portail clients',
    noMobiliarLogin: 'pas de login',
    partnerRoles: 'Rôles de partenaire',
    bankAccount: 'Compte bancaire',
    partnerRelations: 'Relations partenaires',
    active: 'actif',
    activePascalCase: 'Actif',
    roles: 'Rôles',
    role: 'Rôle',
    terminated: 'Terminé',
    hasContracts: 'A des contrats',
    inactive: 'Inactif',
    contracts: 'Contrats',
    offers: 'Offres',
    documents: 'Documents',
    claims: 'Sinistres',
    claimADamage: 'Déclarer un sinistre',
    pending: 'En suspens',
    finished: 'Liquidé',
    showAllClaims: 'Afficher tous les sinistres',
    addPartner: 'Ajouter partenaire',
    loginToContinue: 'Veuillez vous connecter pour continuer.',
    networkNotAvailableForDownloadingData:
        'Les données ne peuvent pas être chargées car vous n’avez aucune connexion réseau. Veuillez réessayer plus tard.',
    searchPartner: 'Chercher un partenaire',
    searchCriteria: 'Critères de recherche',
    numberType: 'Type de numéro',
    partnerNumber: 'Numéro de partenaire',
    contractNumber: 'Numéro de contrat',
    number: 'Numéro',
    invalidText: 'Texte non valable',
    emptyPartnerNumber: 'Veuillez indiquer un numéro de partenaire pour la recherche',
    invalidPartnerNumber: 'Numéro de partenaire non valable',
    emptyContractNumber: 'Veuillez indiquer un numéro de contrat pour la recherche',
    invalidContractNumber: 'Numéro de contrat non valable',
    invalidZipPlace: 'Veuillez indiquer un NPA/un lieu pour la recherche',
    invalidLastNameCompany: 'Veuillez indiquer un nom ou une raison sociale pour la recherche',
    lastName: 'Nom/raison sociale',
    firstName: 'Prénom/raison sociale',
    zipPlace: 'NPA, lieu',
    street: 'Rue',
    noPartnerMatchWithSearchCondition: 'Aucun partenaire n’a été trouvé avec les critères de recherche indiqués',
    search: 'Chercher',
    loadingData: 'Les données sont en cours de chargement...',
    errorWhenLoadPartnerBasicData:
        'Une erreur inattendue s’est produite. Veuillez réessayer de charger le partenaire ultérieurement.',
    singleOffer: '1 offre',
    manyOffers: '{{count}} offres',
    requireNetworkForDownload: 'Vous devez être connecté à un réseau pour télécharger un document.',
    downloadDocumentError:
        'En raison d’une erreur inattendue, le téléchargement du document a échoué. Veuillez réessayer plus tard.',
    downloadingContractDocument: 'Le document contractuel est en cours de téléchargement. Veuillez patienter...',
    noContract: 'Aucun contrat',
    noOffer: 'Aucune offre',
    partnerDoesNotHaveContractYet: 'Ce partenaire n’a aucun contrat',
    partnerDoesNotHaveOfferYet:
        'Ce partenaire n’a aucune offre. Vous pouvez établir des offres sur le portail B2E. Elles seront alors affichées ici.',
    callBack: 'Rappel',
    showAllCallBackTasks: 'Afficher toutes les tâches de rappel',
    callBackTaskDetails: 'Détails de la tâche de rappel',
    description: 'Description',
    dueDate: 'Échéance',
    created: 'Créé',
    creator: 'Auteur-e',
    completeLater: 'Liquider ultérieurement',
    complete: 'Liquider',
    phone: 'Téléphone',
    tasks: 'Tâches',
    emptyTaskListTitle: 'Notices téléphoniques du portail B2E',
    emptyTaskListDescription: 'Les notices téléphoniques créées dans le portail B2E apparaissent ici.',
    cannotCompleteTask:
        'Une erreur s’est produite lors du traitement de la tâche. Veuillez ressayer plus tard ou contactez le Service Desk.',
    document: 'Document',
    downloadingPartnerDocument: 'Le document de partenaire est en cours de téléchargement. Veuillez patienter...',
    partnerDoesNotHaveAnyRelations: 'Ce partenaire n’a aucune relation partenaire.',
    noPartnerRelations: 'Aucune relation partenaire',
    unableToLoadInformation: 'Les informations ne peuvent pas être chargées',
    unableToLoadInformationMessage:
        'L’app ne peut pas charger les données partenaires. Cliquez sur «Synchroniser» pour réessayer.',
    cancel: 'Annuler',
    switch: 'Basculer',
    switchToRelatedPartner: 'Basculer vers la relation partenaire',
    switchToRelatedPartnerDescription: 'Vous pouvez retourner au partenaire actuel en passant par la page d’accueil.',
    settings: 'Paramètres',
    configuration: 'Configuration',
    languageSelection: 'Langue',
    keepDownloadedPartnersOnDevice: 'Conserver les partenaires téléchargés sur l’appareil.',
    cleaningExpiredPartner: '1 partenaire en cours de suppression de l’appareil',
    cleaningExpiredPartners: '{{count}} partenaires en cours de suppression de l’appareil',
    logout: 'Se déconnecter',
    startPhoneCall: 'Lancer un appel téléphonique',
    noNumberAvailable: 'Aucun numéro disponible.',
    noEmailAvailable: 'Aucune adresse e-mail disponible.',
    noLocationAvailable: 'Aucun lieu disponible.',
    place: 'Lieu',
    event: 'Événement',
    noClaim: 'Aucun sinistre disponible',
    noClaimMessage: 'Ce partenaire n’a aucun sinistre.',
    errorLoadingClaimResponsibleEmployee:
        'Les informations sur le collaborateur/la collaboratrice responsable ne peuvent pas être affichées pour le moment.',
    errorLoadingClaimLocation: 'Les informations sur le lieu ne peuvent pas être affichées pour le moment.',
    errorLoadingPayment: 'Les informations relatives au paiement ne peuvent pas être affichées pour le moment.',
    responsibleEmployee: 'Responsable',
    manyClaims: '{{count}} sinistres en suspens',
    singleClaim: '1 sinistre en suspens',
    manyDocuments: '{{count}} documents',
    singleDocument: '1 document',
    synchronizationIncomplete: 'Synchronisation incomplète',
    synchronizationIncompleteMessage:
        'L’app n’a pas pu synchroniser toutes les données. Vous pouvez utiliser les partenaires déjà consultés, mais leurs données pourraient ne pas être à jour.',
    outdatedInformation: 'Données obsolètes',
    outdatedInformationMessage:
        'L’app n’a pas pu mettre à jour les données partenaires. Les données affichées ont été mises à jour pour la dernière fois le {{time}}',
    noDocuments: 'Aucun document',
    noDocumentsMessage:
        'Ce partenaire n’a aucun document. Vous pouvez numériser et ajouter des documents à ce partenaire, p. ex. des documents officiels, une lettre de résiliation, des informations fiduciaires, etc.',
    CRAIsNotAvailable: 'L’app Sinistres (Claim Registration) n’est pas installée.',
    CRAIsNotAvailableMessage:
        'Si vous installez l’app Sinistres (Claim Registration), vous pourrez directement déclarer un cas de sinistre pour ce partenaire!',
    scanbotSDKLicenseExpired: 'La licence a expiré.',
    scanbotSDKLicense: 'Licence ScanBot ',
    documentPreview: 'Aperçu du document',
    documentName: 'Nom du document',
    documentCategories: 'Catégorie et type du document',
    discardDocumentTitle: 'Rejeter document?',
    discardDocumentMessage: 'Vous êtes en train de rejeter le présent document.',
    discard: 'Rejeter',
    keep: 'Conserver',
    loadingImage: 'Les images sont chargées...',
    scanningDocument: 'Le document est numérisé. Veuillez patienter...',
    add: 'Ajouter',
    categoryMissing: 'Il manque la catégorie.',
    categoryMissingMessage:
        'Veuillez attribuer une catégorie au document afin qu’il puisse être retrouvé facilement plus tard.',
    documentNameMissing: 'Il manque le nom du document.',
    documentNameMissingMessage: 'Veuillez mettre à jour le nom du document.',
    save: 'Enregistrer',
    addDocument: 'Ajouter document',
    done: 'Terminé',
    savingDocument: 'Le document est enregistré. Veuillez patienter...',
    saveDocumentTitle: 'Enregistrer document',
    saveDocumentFail: 'Une erreur inattendue s’est produite. Veuillez réessayer plus tard.',
    deleteThisPageTitle: 'Supprimer page?',
    deleteThisPageMessage: 'Vous êtes en train de supprimer la présente page.',
    uploadingMessage: 'Veuillez patienter pendant que votre document est téléversé.',
    uploaded: 'Téléversé',
    failed: 'Échec',
    of: 'de',
    networkNotAvailableForUploadPartnerDocument:
        'Pour téléverser un document, vous avez besoin d’une connexion réseau. Le document numérisé est enregistré sur votre appareil. Essayez ultérieurement, quand vous aurez une connexion réseau, de téléverser le document en choisissant le bouton de synchronization dans l’en-tête.',
    uploadDocumentFailed: 'Échec du téléversement',
    uploadDocumentFailedMessage:
        'L’app n’a pas pu synchroniser toutes les données. Vous pouvez utiliser les partenaires déjà consultés, mais leurs données pourraient ne pas être à jour.',
    uploadDocumentTitle: 'Les documents sont téléversés.',
    delete: 'Effacer',
    documentType: 'Type de document',
    foreignContracts: 'Contrats de la concurrence',
    foreignContract: 'Contrat de la concurrence',
    insuranceType: 'Type de contrat',
    insuranceProvider: "Compagnie d'assurance",
    expirationDate: "Date d'expiration",
    additionalAttributes: 'Autres attributs',
    objectRisk: 'Objet ou risque assuré',
    annualPremium: 'Prime annuelle',
    policeNumber: 'Numéro de contrat ou de police',
    remarks: 'Remarques',
    expirationDateHintTitle: 'Opportunité de vente',
    expirationDateHintDescription:
        "En fixant une date d'expiration, une opportunité de vente est automatiquement générée dans le PdD.",
    addForeignContract: 'Ajouter contrat de la concurrence',
    incompleteForeignContractTitle: 'Contrat de la concurrence incomplet',
    incompleteForeignContractContent:
        'Veuillez compléter les informations manquantes pour que le contrat de la concurrence puisse être ajouté.',
    incompletePartnerDocumentTitle: 'Document partenaire incomplet',
    incompletePartnerDocumentContent:
        'Veuillez compléter les informations manquantes pour que le document partenaire puisse être ajouté.',
    showAllContracts: 'Afficher tous les contrats',
    foreignContractDetails: 'Détails du contrat de la concurrence',
    documentPascalCase: 'Document',
    uploadingForeignContractMessage:
        'Veuillez patienter pendant le téléchargement des nouveaux contrats de la concurrence.',
    invalidInsuranceProviderTitle: 'Assureur/assurance manquant',
    invalidInsuranceProviderMessage: "Veuillez indiquer le nom de l'assureur/de l'assurance.",
    tooManySearchResultTitle: 'Trop de résultats de recherche',
    tooManySearchResultMessage:
        'Veuillez affiner vos critères de recherche si vous ne trouvez pas le partenaire que vous recherchez.',
    claimNumber: 'Numéro de sinistre',
    phoneNumber: 'Numéro de téléphone',
    vehicleRegistrationNumber: "Numéro d'immatriculation",
    invalidVehicleRegistrationNumber:
        "Le canton n'est pas reconnu. Veuillez entrer un code valide de 2 lettres, p.e. 'BE'.",
    attachments: 'Pièces jointes',
    foreignContractsCamelCaseMany: '{{count}} contrats de la concurrence',
    foreignContractsCamelCaseSingle: '1 contrat de la concurrence',
    toUpload: '{{count}} à télécharger',
    myMobiliar: 'Ma Mobilière',
    responsibleAgent: 'Conseiller en assurances',
    unmarkAsFavorite: 'Supprimer de la liste des favoris',
    markAsFavorite: 'Enregistrer dans les favoris',
    synchronizePartnerData: 'Synchroniser les données partenaires',
    downloadAllDocuments: 'Télécharger tous les documents',
    createNewTask: 'Créer une tâche de texte libre',
    unmarkPartnerAsFavoriteConfirmTitle: 'Supprimer {{partnerName}} de la liste des favoris',
    unmarkPartnerAsFavoriteConfirmMessage:
        'Supprimer un partenaire de la liste des favoris entraîne également sa suppression de la liste des favoris dans le portail B2E.',
    unmark: 'Supprimer',
    partnerActions: 'Actions liées au partenaire',
    downloadingAllDocuments: 'Télécharger tous les documents...',
    downloadedCount: 'Téléchargé: {{countStatus}} document(s) sur {{total}}',
    allDownloadedDocuments: 'Tous les documents ont été téléchargés',
    noMoreDocumentsToDownload: 'Il n’y a plus de document à télécharger',
    errorWhileDownloading: 'Erreur au cours du téléchargement',
    failedDownloadCount: 'Le téléchargement de {{countStatus}} document(s) sur {{total}} a échoué',
    failedDownloadDocumentTitle: 'Download all documents failed',
    failedMessageOnNotificationModal:
        'The app was not able to finish the action. Make sure that you have a stable connection while downloading. Click to try again.',
    retry: 'Réessayer',
    quickSearch: 'Recherche rapide',
    partnerSearch: 'Recherche de partenaire',
    newFreeTextTask: 'Nouvelle tâche de texte libre',
    subject: 'Objet',
    responsible: 'Responsable',
    startDate: 'Commence le',
    comment: 'Commentaire',
    forwardWhenHandingOverCase: 'Transmettre lors du transfert du cas',
    create: 'Créer',
    discardFreeTextTaskTitle: 'Annuler la création de la tâche?',
    discardFreeTextTaskMessage: 'Vous êtes sur le point d’annuler la création de la présente tâche',
    incompleteFreeTextTaskTitle: 'Champ «Objet» manquant',
    incompleteFreeTextTaskContent: 'Veuillez compléter les données manquantes pour que la tâche puisse être créée.',
    creatingFreeTextTask: 'Tâche de texte libre en cours de création',
    responsibleCommunicationsActionHeader: 'Actions liées au CEA <<{{agentName}}>>',
    responsiblePhoneCallAction: 'Appel:{{phone}}',
    responsibleEmailAction: 'E-Mail:{{email}}',
    myMobiliarActions: 'Actions liées à Ma Mobilière',
    generateNewActivationCode: 'Générer un nouveau code d’activation',
    generateActivationCode: 'Générer un code d’activation',
    displayActivationCode: 'Afficher le code d’activation',
    yourPersonalActivationCode: 'Votre code d’activation personnel',
    'validUntil.singular': 'Valable jusqu’au: {{expiryDate}} ({{dayLeft}} jour)',
    'validUntil.plural': 'Valable jusqu’au: {{expiryDate}} ({{dayLeft}} jours)',
    partnerIdentification: 'Identification du partenaire',
    pNumber: 'Numéro P',
    contactEmail: 'Adresse e-mail de contact',
    contactMobileNumber: 'Numéro de téléphone portable de contact',
    partnerIdentificationConfirmMessage: 'Veuillez confirmer que vous avez clairement identifié le partenaire',
    confirm: 'Confirmer',
    generatingActivationCode: 'Le code d’activation est généré. Veuillez patienter…',
    cannotGenerateActivationCode: 'Le code d’activation ne peut pas être généré. Veuillez réessayer plus tard.',
    courseOfEvents: 'Déroulement',
    damageDate: 'Date',
    responsibleForClaim: 'Responsable du sinistre',
    responsibleForPartialClaim: 'Responsable du cas partiel',
    partialClaimNumber: 'Numéro du cas partiel',
    status: 'État',
    furtherPartialClaims: 'Autres cas partiels',
    hidePartialClaims: 'Masquer les cas partiels',
    claimDetails: 'Aperçu du sinistre',
    errorLoadingDamageDate: 'Les informations sur la date du sinistre ne peuvent pas être affichées pour le moment',
    errorLoadingCourseOfEvents: 'Les informations sur le déroulement ne peuvent pas être affichées pour le moment',
    errorLoadingCoverage: 'Les informations sur la couverture ne peuvent pas être affichées pour le moment',
    yes: 'Oui',
    no: 'Non',
    missingClaimsTitle: 'Sinistres manquants',
    missingClaimsDescription:
        'Malheureusement, les sinistres qui ont été enregistrées avant la mi-avril 2017 ne peuvent pas être affichées pour le moment.',
    payments: 'Paiements',
    compensation: 'Charge nette indemnités',
    netCosts: 'Charge nette frais',
    notifications: 'Notifications',
    partnersWithError: 'Partenaires avec des erreurs',
    partnersWithBackgroundTasks: 'Partenaires ayant des tâches de fond',
    connectionError: 'Erreur de connexion',
    requireInternetForAction: "Vous avez besoin d'une connexion Internet pour lancer cette action.",
    actionDownloadAllTitle: 'Action Télécharger tous les documents',
    actionIsRunning: "Cette action est déjà en cours. Veuillez attendre qu'elle soit terminée.",
    synchronizingPartnerData: 'Synchronizing partner data...',
    pleaseWait: 'Please wait a moment...',
    synchronizationFailed: 'Synchronization failed',
    actionSynchronizationTitle: 'Action Synchronize partner data',
    actionMarkAsFavorite: 'Action Mark as favorite',
    actionUnnmarkAsFavorite: 'Action Unmark as favorite',
    actionCreateFreeTextTaskTitle: 'Action Create free text task',
    actionScanDocumentTitle: 'Action Scan document',
    actionScanForeignContractTitle: 'Action Scan foreign contract',
    otherActionIsRunning: 'Other action is running. Please wait until it is finished.',
    coverageUnknown: 'Couverture inconnue',
    uploadingDocuments: 'Uploading document(s)...'
};
