export {germanTranslation};

const germanTranslation = {
    networkNotAvailableToInit: 'Sie haben keine Netzwerkverbindung. The App kann nicht eingerichtet werden.',
    networkNotAvailableToSelectPartner: 'Sie können diesen Partner nicht laden, da Sie keine Netzwerkverbindung haben.',
    userHaveToLogin: 'Sie müssen sich zuerst anmelden. Ohne Anmeldung kann die App nicht verwendet werden.',
    waitingForInitialised: 'Die App wird eingerichtet. Bitte warten Sie einen Moment...',
    errorWhenInitialised:
        'Die App konnte nicht eingerichtet werden. Bitte schliessen Sie die App und versuchen Sie es später wieder.',
    favorites: 'Favoriten',
    recent: 'Kürzlich',
    partner: 'Partner',
    removePartner: 'Diesen Partner vom Gerät entfernen',
    markedPartners: 'Markierte Partner vom B2E Portal',
    locallySavedPartners: 'Lokal gespeicherte Partner',
    emptyFavoritesTitle: 'Benutzen Sie die Favoriten aus dem B2E-Portal',
    emptyFavoritesContent:
        'Alle Partner, welche Sie als "Favoriten" (Stern) im B2E-Portal markieren, erscheinen hier und müssen nicht manuell gesucht werden. Markieren Sie Ihre wichtigsten Kunden im B2E-Portal als Favoriten und steigern Sie Ihre Effizienz!',
    basicData: 'Grunddaten',
    telephoneNumber: 'Telefon Privat',
    mobileNumber: 'Mobiltelefon',
    businessNumber: 'Telefon Geschäft',
    email: 'E-Mail',
    address: 'Adresse',
    profession: 'Beruf',
    customerPortal: 'Kundenportal',
    noMobiliarLogin: 'hat kein Kundenlogin',
    partnerRoles: 'Partnerrollen',
    bankAccount: 'Bankkonto',
    partnerRelations: 'Partnerbeziehungen',
    active: 'aktiv',
    activePascalCase: 'Aktiv',
    roles: 'Rollen',
    role: 'Rolle',
    terminated: 'Beendet',
    hasContracts: 'Hat Verträge',
    inactive: 'Inaktiv',
    contracts: 'Verträge',
    offers: 'Angebote',
    documents: 'Dokumente',
    claims: 'Schäden',
    claimADamage: 'Schaden melden',
    pending: 'Pendent',
    finished: 'Abgeschlossen',
    showAllClaims: 'Alle Schäden anzeigen',
    addPartner: 'Partner hinzufügen',
    loginToContinue: 'Bitte melden Sie sich an um fortzufahren.',
    networkNotAvailableForDownloadingData:
        'Die Daten können nicht geladen werden, da Sie keine Netzwerkverbindung haben. Bitte versuchen Sie es später wieder.',
    searchPartner: 'Partner suchen',
    searchCriteria: 'Suchkriterien',
    numberType: 'Nummerntyp',
    partnerNumber: 'Partnernummer',
    contractNumber: 'Vertragsnummer',
    number: 'Nummer',
    invalidText: 'Ungültiger text',
    emptyPartnerNumber: 'Bitte geben Sie eine Partnernummer für die Suche ein',
    invalidPartnerNumber: 'Ungültige Partnernummer',
    emptyContractNumber: 'Bitte geben Sie eine Vertragsnummer für die Suche ein',
    invalidContractNumber: 'Ungültige Vertragsnummer',
    invalidZipPlace: 'Bitte geben Sie eine PLZ/einen Ort für die Suche ein',
    invalidLastNameCompany: 'Bitte geben Sie einen Nachnamen oder Firmennamen für die Suche ein',
    lastName: 'Name/Firma',
    firstName: 'Vorname/Firma',
    zipPlace: 'PLZ Ort',
    street: 'Strasse',
    noPartnerMatchWithSearchCondition: 'Mit Ihren Suchkriterien wurden keine Partner gefunden',
    search: 'Suchen',
    loadingData: 'Daten werden geladen...',
    errorWhenLoadPartnerBasicData:
        'Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie später wieder den Partner zu laden.',
    singleOffer: '1 Angebot',
    manyOffers: '{{count}} Angebote',
    requireNetworkForDownload: 'Sie müssen online sein, um ein Dokument herunterzuladen.',
    downloadDocumentError:
        'Das Dokument konnte aus unerwarteten Gründen nicht heruntergeladen werden. Bitte versuchen Sie es später wieder.',
    downloadingContractDocument: 'Das Vertragsdokument wird heruntergeladen. Bitte warten Sie einen Moment...',
    noContract: 'Keine Verträge',
    noOffer: 'Keine Angebote',
    partnerDoesNotHaveContractYet: 'Dieser Partner hat keine Verträge',
    partnerDoesNotHaveOfferYet:
        'Dieser Partner hat keine Angebote. Sie können Angebote im B2E-Portal erstellen. Diese werden dann hier angezeigt.',
    callBack: 'Rückruf',
    showAllCallBackTasks: 'Alle Rückrufaufgaben anzeigen',
    callBackTaskDetails: 'Rückrufaufgabe Details',
    description: 'Beschreibung',
    dueDate: 'Fälligkeit',
    created: 'Erstellt',
    creator: 'Ersteller/in',
    completeLater: 'Später erledigen',
    complete: 'Erledigen',
    phone: 'Telefon',
    tasks: 'Aufgaben',
    emptyTaskListTitle: 'Rückrufaufgaben aus dem B2E-Portal',
    emptyTaskListDescription: 'Im B2E-Portal können Rückrufaufgaben erstellt werden. Diese werden hier angezeigt.',
    cannotCompleteTask:
        'Bei der Aufgabenerledigung ist ein Fehler aufgetreten. Bitte versuchen Sie es später wieder oder kontaktieren Sie den Servicedesk.',
    document: 'Dokument',
    downloadingPartnerDocument: 'Das Partnerdokument wird heruntergeladen. Bitte warten Sie einen Moment...',
    partnerDoesNotHaveAnyRelations: 'Dieser Partner hat keine Partnerbeziehungen.',
    noPartnerRelations: 'Keine Partnerbeziehungen',
    unableToLoadInformation: 'Information kann nicht geladen werden',
    unableToLoadInformationMessage:
        'Die App kann die Partnerdaten nicht laden. Wählen Sie ""Synchronisieren"" um es wieder zu versuchen.',
    cancel: 'Abbrechen',
    switch: 'Wechseln',
    switchToRelatedPartner: 'Zur Partnerbeziehung wechseln',
    switchToRelatedPartnerDescription: 'Sie können über die Startseite zum aktuellen Partner zurückkehren.',
    settings: 'Einstellungen',
    configuration: 'Konfiguration',
    languageSelection: 'Sprache',
    keepDownloadedPartnersOnDevice: 'Heruntergeladene Partner auf dem Gerät behalten',
    cleaningExpiredPartner: '1 Partner wird vom Gerät entfernt',
    cleaningExpiredPartners: '{{count}} Partner werden vom Gerät entfernt',
    logout: 'Abmelden',
    startPhoneCall: 'Telefonanruf starten',
    noNumberAvailable: 'Es ist keine Nummer verfügbar.',
    noEmailAvailable: 'Es ist keine E-Mail-Adresse verfügbar.',
    noLocationAvailable: 'Es ist kein Standort verfügbar.',
    place: 'Ort',
    event: 'Ereignis',
    noClaim: 'Kein Schaden vorhanden',
    noClaimMessage: 'Dieser Partner hat keine Schäden.',
    errorLoadingClaimResponsibleEmployee:
        'Die Information zum verantwortlichen Mitarbeiter/zur verantwortlichen Mitarbeiterin kann im Moment nicht angezeigt werden.',
    errorLoadingClaimLocation: 'Die Information zum Standort kann im Moment nicht angezeigt werden.',
    errorLoadingPayment: 'Die Zahlungsinformationen können im Moment nicht angezeigt werden.',
    responsibleEmployee: 'Verantwortliche/r',
    manyClaims: '{{count}} pendente Schäden',
    singleClaim: '1 pendenter Schaden',
    manyDocuments: '{{count}} Dokumente',
    singleDocument: '1 Dokument',
    synchronizationIncomplete: 'Synchronisation unvollständig',
    synchronizationIncompleteMessage:
        'Die App konnte nicht alle Daten synchronisieren. Sie können die bereits angesehenen Partner verwenden. Allerdings könnten deren Daten veraltet sein.',
    outdatedInformation: 'Veraltete Daten',
    outdatedInformationMessage:
        'Die App konnte die Partnerdaten nicht aktualisieren. Die angezeigten Daten wurden zuletzt aktualisiert am {{time}}',
    noDocuments: 'Keine Dokumente',
    noDocumentsMessage:
        'Dieser Partner hat keine Dokumente. Sie können Dokumente zu diesem Partner scannen und hinzufügen, z.B. Amtliche Dokumente, Kündigungsschreiben, Treuhänderinformation usw..',
    CRAIsNotAvailable: 'Die Schadenapp (Claim Registration App) ist nicht installiert.',
    CRAIsNotAvailableMessage:
        'Wenn Sie die Schadenapp (Claim Registration App) installieren, können Sie direkt Schadenfälle für diesen Partner anmelden!',
    scanbotSDKLicenseExpired: 'Die Lizenz ist abgelaufen',
    scanbotSDKLicense: 'ScanBot Lizenz',
    documentPreview: 'Dokument Vorschau',
    documentName: 'Dokument name',
    documentCategories: 'Dokument Kategorie und Typ',
    discardDocumentTitle: 'Dokument verwerfen?',
    discardDocumentMessage: 'Sie sind dabei, das vorliegende Dokument zu verwerfen',
    discard: 'Verwerfen',
    keep: 'Behalten',
    loadingImage: 'Die Bilder werden geladen…',
    scanningDocument: 'Das Dokument wird gescannt. Biite warten…',
    add: 'Hinzufügen',
    categoryMissing: 'Die Kategorie fehlt',
    categoryMissingMessage: 'Bitte kategorisieren Sie das Dokument, damit es später einfacher gefunden werden kann.',
    documentNameMissing: 'Der Dokument Name fehlt',
    documentNameMissingMessage: 'Bitte aktualisieren Sie den Dokument Namen',
    save: 'Speichern',
    addDocument: 'Dokument hinzufügen',
    done: 'Fertig',
    savingDocument: 'Das Dokument wird gespeichert. Bitte warten…',
    saveDocumentTitle: 'Dokument speichern',
    saveDocumentFail: 'Ein unerwarteter Fehler ist passiert. Bitte versuchen Sie es später wieder.',
    deleteThisPageTitle: 'Seite entfernen?',
    deleteThisPageMessage: 'Sie sind dabei, die vorliegende Seite zu entfernen.',
    uploadingMessage: 'Bitte warten Sie, während Ihr Dokument hochgeladen wird.',
    uploaded: 'Hochgeladen',
    failed: 'Gescheitert',
    of: 'von',
    networkNotAvailableForUploadPartnerDocument:
        'Um ein Dokument hochzuladen, brauchen Sie eine Netzwerkverbindung. Das gescannte Dokument ist auf Ihrem Gerät gespeichert. Versuchen Sie später, wenn Sie eine Netzwerkverbindung haben, das Dokument hochzuladen, indem Sie den Synchronisationsbutton im Header wählen.',
    uploadDocumentFailed: 'Upload gescheitert',
    uploadDocumentFailedMessage:
        'Die App konnte nicht alle Daten synchronisieren. Sie können die bereits angesehenen Partner verwenden. Allerdings könnten deren Daten veraltet sein.',
    uploadDocumentTitle: 'Die Dokumente werden hochgeladen',
    delete: 'Löschen',
    documentType: 'Dokument Typ',
    foreignContracts: 'Fremdverträge',
    foreignContract: 'Fremdvertrag',
    insuranceType: 'Vertragstyp',
    insuranceProvider: 'Versicherungsgesellschaft',
    expirationDate: 'Ablaufdatum',
    additionalAttributes: 'Weitere Attribute',
    objectRisk: 'Versichertes Objekt oder Risiko',
    annualPremium: 'Jahresprämie (CHF)',
    policeNumber: 'Vertrags- oder Policennummer',
    remarks: 'Bemerkungen',
    expirationDateHintTitle: 'Verkaufschance',
    expirationDateHintDescription:
        'Durch Setzen eines Ablaufdatums wird in der VP automatisch eine Verkaufschance generiert.',
    addForeignContract: 'Fremdvertrag hinzufügen',
    incompleteForeignContractTitle: 'Unvollständiger Fremdvertrag',
    incompleteForeignContractContent:
        'Bitte ergänzen Sie die fehlenden Angaben, damit der Fremdvertrag hinzugefügt werden kann.',
    incompletePartnerDocumentTitle: 'Unvollständiges Partnerdokument',
    incompletePartnerDocumentContent:
        'Bitte ergänzen Sie die fehlenden Angaben, damit das Parterdokument hinzugefügt werden kann.',
    showAllContracts: 'Alle Verträge anzeigen',
    foreignContractDetails: 'Fremdvertrag Details',
    documentPascalCase: 'Dokument',
    uploadingForeignContractMessage: 'Bitte warten Sie, während die neuen Fremdverträge hochgeladen werden.',
    invalidInsuranceProviderTitle: 'Versicherer/Versicherung fehlt',
    invalidInsuranceProviderMessage: "Bitte geben Sie den Namen des 'Versicherers/Versicherung' an.",
    tooManySearchResultTitle: 'Zu viele Suchergebnisse',
    tooManySearchResultMessage:
        'Bitte verfeinern Sie die Suchkriterien, wenn Sie den gesuchten Partner nicht im Suchergebnis vorfinden.',
    claimNumber: 'Schadennummer',
    phoneNumber: 'Telefonnummer',
    vehicleRegistrationNumber: 'Nummernschild',
    invalidVehicleRegistrationNumber:
        "Der Kanton wird nicht erkannt. Bitte geben Sie einen gülten 2-Buchstaben-Code ein, z.B. 'BE'.",
    attachments: 'Anhänge',
    foreignContractsCamelCaseMany: '{{count}} Fremdverträge',
    foreignContractsCamelCaseSingle: '1 Fremdvertrag',
    toUpload: '{{count}} hochzuladen',
    myMobiliar: 'Meine Mobiliar',
    responsibleAgent: 'Versicherungsberater',
    unmarkAsFavorite: 'Aus Favoritenliste entfernen',
    markAsFavorite: 'Als Favoriten speichern',
    synchronizePartnerData: 'Partnerdaten synchronisieren',
    downloadAllDocuments: 'Alle Dokumente herunterladen',
    createNewTask: 'Freitextaufgabe erstellen',
    unmarkPartnerAsFavoriteConfirmTitle: '{{partnerName}} aus Favoritenliste entfernen',
    unmarkPartnerAsFavoriteConfirmMessage:
        'Aus Favoritenliste entfernen führt dazu, dass dieser Partner ebenfalls aus der Favoritenliste im B2E-Portal entfernt wird.',
    unmark: 'Nicht markieren',
    partnerActions: 'Partner Aktionen',
    downloadingAllDocuments: 'Alle Dokumente herunterladen...',
    downloadedCount: 'Heruntergeladen: {{countStatus}} von {{total}} Dokumenten',
    allDownloadedDocuments: 'Alle Dokumente wurden heruntergeladen',
    noMoreDocumentsToDownload: 'Es gibt keine Dokumente mehr zum Herunterladen',
    errorWhileDownloading: 'Fehler während dem Herunterladen',
    failedDownloadCount: '{{countStatus}} von {{total}} Dokumenten fehlgeschlagen',
    failedDownloadDocumentTitle: 'Download all documents failed',
    failedMessageOnNotificationModal:
        'The app was not able to finish the action. Make sure that you have a stable connection while downloading. Click to try again.',
    retry: 'Wiederholen',
    quickSearch: 'Schnellsuche',
    partnerSearch: 'Partnersuche',
    newFreeTextTask: 'Neue Freitextaufgabe',
    subject: 'Betreff',
    responsible: 'Verantwortlicher',
    startDate: 'Beginnt am',
    comment: 'Kommentar',
    forwardWhenHandingOverCase: 'Weiterleiten bei Fallübergabe',
    create: 'Erstellen',
    discardFreeTextTaskTitle: 'Aufgabenerstellung abbrechen?',
    discardFreeTextTaskMessage: 'Sie sind dabei, die vorliegende Aufgabenerstellung zu verwerfen',
    incompleteFreeTextTaskTitle: 'Fehlendes Betreff-Feld',
    incompleteFreeTextTaskContent: 'Bitte ergänzen Sie die fehlenden Angaben, damit die Aufgabe erstellt werden kann.',
    creatingFreeTextTask: 'Freitextaufgabe wird erstellt',
    responsibleCommunicationsActionHeader: 'VB <<{{agentName}}>> Aktionen',
    responsiblePhoneCallAction: 'Anruf:{{phone}}',
    responsibleEmailAction: 'E-Mail:{{email}}',
    myMobiliarActions: 'Meine Mobiliar Aktionen',
    generateNewActivationCode: 'Neuen Aktivierungscode generieren',
    generateActivationCode: 'Aktivierungscode generieren',
    displayActivationCode: 'Aktivierungscode anzeigen',
    yourPersonalActivationCode: 'Ihr persönlicher Aktivierungscode',
    'validUntil.singular': 'Gültig bis: {{expiryDate}} ({{dayLeft}} Tag)',
    'validUntil.plural': 'Gültig bis: {{expiryDate}} ({{dayLeft}} Tage)',
    partnerIdentification: 'Partner Identifikation',
    pNumber: 'P-Nummer',
    contactEmail: 'Kontakt E-Mail',
    contactMobileNumber: 'Kontakt Mobiltelefon',
    partnerIdentificationConfirmMessage: 'Bitte bestätigen Sie, dass Sie diesen Partner eindeutig identifiziert haben',
    confirm: 'Bestätigen',
    generatingActivationCode: 'Aktivierungscode wird generiert. Bitte warten Sie einen Moment…',
    cannotGenerateActivationCode:
        'Der Aktivierungscode kann nicht generiert werden. Bitte versuchen Sie es später wieder.',
    courseOfEvents: 'Hergang',
    damageDate: 'Datum',
    responsibleForClaim: 'Schaden Verantwortlicher',
    responsibleForPartialClaim: 'Teilfall Verantwortlicher',
    partialClaimNumber: 'Teilfall Nummer',
    status: 'Status',
    furtherPartialClaims: 'Weitere Teilfälle',
    hidePartialClaims: 'Teilfälle ausblenden',
    claimDetails: 'Schadenübersicht',
    errorLoadingDamageDate: 'Informationen über das Schadendatum können im Moment nicht angezeigt werden',
    errorLoadingCourseOfEvents: 'Informationen über den Hergang können im Moment nicht angezeigt werden',
    errorLoadingCoverage: 'Informationen über die Deckung können im Moment nicht angezeigt werden',
    yes: 'Ja',
    no: 'Nein',
    missingClaimsTitle: 'Fehlende Schadenfälle',
    missingClaimsDescription:
        'Schadenfälle, die vor Mitte April 2017 erfasst wurden, können leider vorläufig nicht angezeigt werden.',
    payments: 'Zahlungen',
    compensation: 'Entschädigungen',
    netCosts: 'Kosten netto',
    notifications: 'Meldungen',
    partnersWithError: 'Partner mit Fehlern',
    partnersWithBackgroundTasks: 'Partner mit Hintergrundaufgaben',
    connectionError: 'Verbindungsfehler',
    requireInternetForAction: 'Sie benötigen eine Internetverbindung, um diese Aktion zu starten.',
    actionDownloadAllTitle: 'Aktion Laden Sie alle Dokumente herunter',
    actionIsRunning: 'Diese Aktion läuft bereits. Bitte warten Sie, bis sie abgeschlossen ist.',
    synchronizingPartnerData: 'Synchronizing partner data...',
    pleaseWait: 'Please wait a moment...',
    synchronizationFailed: 'Synchronization failed',
    actionSynchronizationTitle: 'Action Synchronize partner data',
    actionMarkAsFavorite: 'Action Mark as favorite',
    actionUnnmarkAsFavorite: 'Action Unmark as favorite',
    actionCreateFreeTextTaskTitle: 'Action Create free text task',
    actionScanDocumentTitle: 'Action Scan document',
    actionScanForeignContractTitle: 'Action Scan foreign contract',
    otherActionIsRunning: 'Other action is running. Please wait until it is finished.',
    coverageUnknown: 'Deckung unbekannt',
    uploadingDocuments: 'Uploading document(s)...'
};
