export {italianTranslation};

const italianTranslation = {
    networkNotAvailableToInit: 'Connessione di rete non disponibile. Impossibile installare l’app.',
    networkNotAvailableToSelectPartner:
        'Impossibile caricare questo partner perché non si dispone di una connessione di rete.',
    userHaveToLogin: 'È necessario prima eseguire il login. Senza autenticazione non è possibile utilizzare l’app.',
    waitingForInitialised: 'L’app viene installata. Attendere...',
    errorWhenInitialised: 'Installazione dell’app fallita. Chiudere l’app e riprovare più tardi.',
    favorites: 'Preferiti',
    recent: 'Recente',
    partner: 'Partner',
    removePartner: 'Rimuovere questo partner dal dispositivo',
    markedPartners: 'Partner contrassegnati dal portale B2E',
    locallySavedPartners: 'Partner salvati localmente',
    emptyFavoritesTitle: 'Utilizzare i preferiti dal portale B2E',
    emptyFavoritesContent:
        'Tutti i partner contrassegnati come «preferiti» (asterisco) nel portale B2E, vengono visualizzati qui e non devono essere cercati manualmente. Contrassegnare come preferiti i propri clienti principali nel portale B2E per incrementare la propria efficienza!',
    basicData: 'Dati di base',
    telephoneNumber: 'Telefono privato',
    mobileNumber: 'Cellulare',
    businessNumber: 'Telefono ufficio',
    email: 'E-mail',
    address: 'Indirizzo',
    profession: 'Professione',
    customerPortal: 'Portale clienti',
    noMobiliarLogin: 'non ha il login',
    partnerRoles: 'Ruoli partner',
    bankAccount: 'Conto bancario',
    partnerRelations: 'Relazioni partner',
    active: 'attivo',
    activePascalCase: 'Attivo',
    roles: 'Ruoli',
    role: 'Ruolo',
    terminated: 'Terminato',
    hasContracts: 'ha contratti',
    inactive: 'Inattivo',
    contracts: 'Contratti',
    offers: 'Offerta',
    documents: 'Documenti',
    claims: 'Sinistri',
    claimADamage: 'Notificare sinistro',
    pending: 'In sospeso',
    finished: 'Terminato',
    showAllClaims: 'Visualizzare tutti i sinistri',
    addPartner: 'Aggiungere partner',
    loginToContinue: 'Per proseguire, effettuare il login.',
    networkNotAvailableForDownloadingData:
        'Impossibile caricare i dati perché non si dispone di una connessione di rete. Riprovare più tardi.',
    searchPartner: 'Cercare partner',
    searchCriteria: 'Criteri di ricerca',
    numberType: 'Tipo di numero',
    partnerNumber: 'Numero partner',
    contractNumber: 'Numero di contratto',
    number: 'Numero',
    invalidText: 'Testo non valido',
    emptyPartnerNumber: 'Inserire un numero partner per la ricerca',
    invalidPartnerNumber: 'Numero partner non valido',
    emptyContractNumber: 'Inserire un numero contratto per la ricerca',
    invalidContractNumber: 'Numero contratto non valido',
    invalidZipPlace: 'Inserire un NPA o una località per la ricerca',
    invalidLastNameCompany: 'Inserire un cognome o una ragione sociale per la ricerca',
    lastName: 'Cognome/Ditta',
    firstName: 'Nome/Ditta',
    zipPlace: 'NPA  Località',
    street: 'Via',
    noPartnerMatchWithSearchCondition: 'Nessun partner trovato per i criteri di ricerca inseriti',
    search: 'Cercare',
    loadingData: 'Caricamento dei dati in corso...',
    errorWhenLoadPartnerBasicData: 'Si è verificato un errore imprevisto. Provare più tardi a ricaricare il partner.',
    singleOffer: '1 offerta',
    manyOffers: '{{count}} offerte',
    requireNetworkForDownload: 'È necessario essere online per scaricare un documento.',
    downloadDocumentError: 'Non è stato possibile scaricare il documento per cause sconosciute. Riprovare più tardi.',
    downloadingContractDocument: 'Download in corso del documento contrattuale. Attendere...',
    noContract: 'Nessun contratto',
    noOffer: 'Nessuna offerta',
    partnerDoesNotHaveContractYet: 'Questo partner non ha contratti.',
    partnerDoesNotHaveOfferYet:
        'Questo partner non ha offerte. È possibile creare offerte nel portale B2E. Le offerte vengono quindi visualizzate qui.',
    callBack: 'Richiamata',
    showAllCallBackTasks: 'Visualizzare tutti i compiti di richiamata',
    callBackTaskDetails: 'Dettagli del compito di richiamata',
    description: 'Descrizione',
    dueDate: 'Scadenza',
    created: 'Creato',
    creator: 'Creato da',
    completeLater: 'Chiudere più tardi',
    complete: 'Chiudere',
    phone: 'Telefono',
    tasks: 'Compiti',
    emptyTaskListTitle: 'Compiti di richiamata dal portale B2E',
    emptyTaskListDescription:
        'Nel portale B2E è possibile creare compiti di richiamata. Le offerte vengono quindi visualizzate qui.',
    cannotCompleteTask:
        'Si è verificato un errore durante l’esecuzione del compito. Riprovare più tardi o contattare il Service Desk.',
    document: 'Documento',
    downloadingPartnerDocument: 'Download in corso del documento del partner. Attendere...',
    partnerDoesNotHaveAnyRelations: 'Questo partner non ha relazioni.',
    noPartnerRelations: 'Nessuna relazione partner',
    unableToLoadInformation: 'Impossibile caricare l’informazione',
    unableToLoadInformationMessage:
        'L’app non riesce a caricare i dati del partner. Selezionare «Sincronizzare» per riprovare.',
    cancel: 'Annullare',
    switch: 'Cambiare',
    switchToRelatedPartner: 'Passare alla relazione partner',
    switchToRelatedPartnerDescription: 'È possibile passare al partner attuale dalla home page.',
    settings: 'Impostazioni',
    configuration: 'Configurazione',
    languageSelection: 'Lingua',
    keepDownloadedPartnersOnDevice: 'Mantenere i partner scaricati sul dispositivo',
    cleaningExpiredPartner: '1 partner viene rimosso dal dispositivo',
    cleaningExpiredPartners: '{{}} partner vengono rimossi dal dispositivo',
    logout: 'Logout',
    startPhoneCall: 'Avviare chiamata telefonica',
    noNumberAvailable: 'Non è disponibile alcun numero.',
    noEmailAvailable: 'Non è disponibile alcun indirizzo e-mail.',
    noLocationAvailable: 'Non è disponibile alcuna sede.',
    place: 'Luogo',
    event: 'Evento',
    noClaim: 'Nessun sinistro presente',
    noClaimMessage: 'Questo partner non ha sinistri.',
    errorLoadingClaimResponsibleEmployee:
        'Al momento non è possibile visualizzare l’informazione sul collaboratore/sulla collaboratrice responsabile.',
    errorLoadingClaimLocation: 'Al momento non è possibile visualizzare l’informazione sulla sede.',
    errorLoadingPayment: 'Le informazioni sul pagamento non possono essere visualizzate al momento.',
    responsibleEmployee: 'Responsabile',
    manyClaims: '{{count}} sinistri pendenti',
    singleClaim: '1 sinistro pendente',
    manyDocuments: '{{count}} documenti',
    singleDocument: '1 documento',
    synchronizationIncomplete: 'Sincronizzazione incompleta',
    synchronizationIncompleteMessage:
        'L’app non è riuscita a sincronizzare tutti i dati. È possibile utilizzare i partner già visualizzati. Tuttavia i loro dati potrebbero essere non aggiornati.',
    outdatedInformation: 'Dati non aggiornati',
    outdatedInformationMessage:
        'L’app non è riuscita ad aggiornare i dati del partner. I dati visualizzati sono stati aggiornati l’ultima volta il {{time}}',
    noDocuments: 'Nessun documento',
    noDocumentsMessage:
        'Questo partner non ha documenti. È possibile scansionare e aggiungere documenti a questo partner, p. es. documenti ufficiali, lettere di disdetta, procure ecc.',
    CRAIsNotAvailable: 'L’app sinistri (Claim Registration App) non è installata.',
    CRAIsNotAvailableMessage:
        'Se si installa l’app sinistri (Claim Registration App), è possibile notificare direttamente i casi di sinistro per questo partner.',
    scanbotSDKLicenseExpired: 'La licenza è scaduta',
    scanbotSDKLicense: 'ScanBot licenza',
    documentPreview: 'Anteprima documento',
    documentName: 'Nome documento',
    documentCategories: 'Categoria e tipo documento',
    discardDocumentTitle: 'Annullare documento?',
    discardDocumentMessage: 'Sta annullando il presente documento',
    discard: 'Annullare',
    keep: 'Mantenere',
    loadingImage: 'Caricamento immagini…',
    scanningDocument: 'Scansione documento... Attendere...',
    add: 'Inserire',
    categoryMissing: 'Manca la categoria',
    categoryMissingMessage: 'Si prega di categorizzare il documento per poterlo trovare più facilmente in seguito.',
    documentNameMissing: 'Manca il nome del documento',
    documentNameMissingMessage: 'Aggiornare il nome del documento',
    save: 'Salvare',
    addDocument: 'Aggiungere documento',
    done: 'Fatto!',
    savingDocument: 'Salvataggio documento... Attendere...',
    saveDocumentTitle: 'Salvare documento',
    saveDocumentFail: 'Si è verificato un errore imprevisto. Si prega di riprovare più tardi.',
    deleteThisPageTitle: 'Eliminare pagina?',
    deleteThisPageMessage: 'Sta eliminando questa pagina',
    uploadingMessage: 'Caricamento del documento. Attendere per favore...',
    uploaded: 'Caricato',
    failed: 'Caricamento fallito',
    of: 'da',
    networkNotAvailableForUploadPartnerDocument:
        "Per caricare un documento è necessario un collegamento in rete. Il documento scansito è salvato sul suo apparecchio. Più tardi, quando dispone di un collegamento in rete, provi a caricare il documento premendo il pulsante per la sincronizzazione nell'intestazione.",
    uploadDocumentFailed: 'Caricamento fallito',
    uploadDocumentFailedMessage:
        "L'app non ha potuto sincronizzare tutti i dati. Può utilizzare i partner già visti. Tuttavia i loro dati potrebbero non essere attuali.",
    uploadDocumentTitle: 'Caricamento dei documenti ',
    delete: 'Cancellare',
    documentType: 'Tipo di documento',
    foreignContracts: 'Contratti con compagnie terze',
    foreignContract: 'Contratto con compagnia terza',
    insuranceType: 'Tipo di contratto',
    insuranceProvider: 'Compagnia assicurativa',
    expirationDate: 'Data di scadenza',
    additionalAttributes: 'Attributi aggiuntivi',
    objectRisk: 'Oggetto o rischio assicurati',
    annualPremium: 'Premio annuo (CHF)',
    policeNumber: 'Numero di contratto o di polizza',
    remarks: 'Osservazioni',
    expirationDateHintTitle: 'Opportunità di vendita',
    expirationDateHintDescription:
        "L'impostazione della data di scadenza attiverà automaticamente un'opportunità di vendita all'interno del portale di vendita (VP).",
    addForeignContract: 'Aggiungere contratto con compagnia terza',
    incompleteForeignContractTitle: 'Contratto con compagnia terza incompleto',
    incompleteForeignContractContent:
        'Per favore, completa le informazioni mancanti per poter aggiungere il contratto.',
    incompletePartnerDocumentTitle: 'Documento incompleto',
    incompletePartnerDocumentContent:
        'Per favore, completa le informazioni mancanti per poter aggiungere il documento.',
    showAllContracts: 'Mostrare tutti i contratti',
    foreignContractDetails: 'Detagli del contratto',
    documentPascalCase: 'Documento',
    uploadingForeignContractMessage: 'Attendere il caricamento dei nuovi contratti.',
    invalidInsuranceProviderTitle: "Manca l'assicuratore/assicurazione",
    invalidInsuranceProviderMessage: "Si prega di indicare il nome dell'assicuratore/assicurazione.",
    tooManySearchResultTitle: 'Troppi risultati di ricerca',
    tooManySearchResultMessage:
        'Perfeziona i criteri di ricerca se non riesci a trovare il partner che stai cercando nel risultato della ricerca.',
    claimNumber: 'Numero del sinistro',
    phoneNumber: 'Numero di telefono',
    vehicleRegistrationNumber: 'Targa',
    invalidVehicleRegistrationNumber:
        "Il Cantone non è riconosciuto. Inserisci un codice valido di 2 lettere, ad es. 'BE'.",
    attachments: 'Allegato',
    foreignContractsCamelCaseMany: '{{count}} contratti con compagnia terza',
    foreignContractsCamelCaseSingle: '1 contratto con compagnia terza',
    toUpload: '{{count}} da caricare',
    myMobiliar: 'La mia Mobiliare',
    responsibleAgent: 'Consulente assicurativo',
    unmarkAsFavorite: 'Rimuovere dai preferiti',
    markAsFavorite: 'Salvare nei favoriti',
    synchronizePartnerData: 'Sincronizzare i dati del partner',
    downloadAllDocuments: 'Scaricare tutti i documenti',
    createNewTask: 'Allestire compito testo libero',
    unmarkPartnerAsFavoriteConfirmTitle: 'Rimuovere {{partnerName}} dai preferiti',
    unmarkPartnerAsFavoriteConfirmMessage:
        'Rimuovere dalla lista dei preferiti significa che anche questo partner viene rimosso dalla lista dei preferiti nel portale B2E.',
    unmark: 'Non selezionare',
    partnerActions: 'Azioni partner',
    downloadingAllDocuments: 'Scaricare tutti i documenti...',
    downloadedCount: 'Scaricati: {{countStatus}} di {{total}} documenti',
    allDownloadedDocuments: 'Tutti i documenti sono stati scaricati',
    noMoreDocumentsToDownload: 'Non ci sono altri documenti da scaricare',
    errorWhileDownloading: 'Errore durante il download',
    failedDownloadCount: 'Download di {{countStatus}} di {{total}} documenti non riuscito',
    failedDownloadDocumentTitle: 'Download all documents failed',
    failedMessageOnNotificationModal:
        'The app was not able to finish the action. Make sure that you have a stable connection while downloading. Click to try again.',
    retry: 'Ripetere',
    quickSearch: 'Ricerca rapida',
    partnerSearch: 'Ricerca partner',
    newFreeTextTask: 'Nuovo testo libero',
    subject: 'Oggetto',
    responsible: 'Responsabile',
    startDate: 'Inizia il',
    comment: 'Commento',
    forwardWhenHandingOverCase: "Inoltrare all'assegnazione del caso",
    create: 'Creare',
    discardFreeTextTaskTitle: 'Interrompere la creazione del compito?',
    discardFreeTextTaskMessage: 'Sta annullando la creazione di questo compito',
    incompleteFreeTextTaskTitle: "Manca il campo dell'oggetto",
    incompleteFreeTextTaskContent:
        'Si prega di completare le informazioni mancanti in modo che il compito possa essere creato.',
    creatingFreeTextTask: 'Creazione nuovo testo libero',
    responsibleCommunicationsActionHeader: 'CA <<{{agentName}}>> azioni',
    responsiblePhoneCallAction: 'Chiamata a:{{phone}}',
    responsibleEmailAction: 'E-Mail:{{email}}',
    myMobiliarActions: 'Azioni La mia mobiliare',
    generateNewActivationCode: 'Generare nuovo codice di attivazione',
    generateActivationCode: 'Generare codice di attivazione',
    displayActivationCode: 'Visualizzare codice di attivazione',
    yourPersonalActivationCode: 'Il suo codice di attivazione personale',
    'validUntil.singular': 'Valido fino al: {{expiryDate}} ({{dayLeft}} giorno)',
    'validUntil.plural': 'Valido fino al: {{expiryDate}} ({{dayLeft}} giorni)',
    partnerIdentification: 'Identificazione partner',
    pNumber: 'N. partner',
    contactEmail: 'Contatto e-mail',
    contactMobileNumber: 'Contatto cellulare',
    partnerIdentificationConfirmMessage: 'Per favore, confermi di aver identificato chiaramente questo partner ',
    confirm: 'Confermare',
    generatingActivationCode: 'Viene generato il codice di attivazione. Attendere...',
    cannotGenerateActivationCode: 'Impossibile generare il codice di attivazione. Si prega di riprovare più tardi.',
    courseOfEvents: 'Dinamica',
    damageDate: 'Data',
    responsibleForClaim: 'Responsabile sinistro',
    responsibleForPartialClaim: 'Responsabile caso parziale',
    partialClaimNumber: 'Numero caso parziale',
    status: 'Stato',
    furtherPartialClaims: 'Altri casi parziali',
    hidePartialClaims: 'Nascondere casi parziali',
    claimDetails: 'Riepilogo dei sinistri',
    errorLoadingDamageDate: 'Al momento le informazioni sulla data del sinistro non possono essere visualizzate',
    errorLoadingCourseOfEvents: 'Al momento le informazioni sulla dinamica non possono essere visualizzate',
    errorLoadingCoverage: 'Al momento le informazioni sulla copertura non possono essere visualizzate',
    yes: 'Sì',
    no: 'No',
    missingClaimsTitle: 'Sinistri mancanti',
    missingClaimsDescription:
        'Purtroppo, i sinistri registrati prima della metà di aprile 2017 non possono por il momento essere visualizzati.',
    payments: 'Pagamenti',
    compensation: 'Onere netto indennità',
    netCosts: 'Onere netto spese',
    notifications: 'Notifiche',
    partnersWithError: 'Partner con errori',
    partnersWithBackgroundTasks: 'Partner con compiti di fondo',
    connectionError: 'Errore di collegamento',
    requireInternetForAction: 'Per avviare questa azione è necessaria una connessione a Internet.',
    actionDownloadAllTitle: 'Azione Scarica tutti i documenti',
    actionIsRunning: 'Questa azione è già in corso. Si prega di attendere fino a quando non è terminata.',
    synchronizingPartnerData: 'Synchronizing partner data...',
    pleaseWait: 'Please wait a moment...',
    synchronizationFailed: 'Synchronization failed',
    actionSynchronizationTitle: 'Action Synchronize partner data',
    actionMarkAsFavorite: 'Action Mark as favorite',
    actionUnnmarkAsFavorite: 'Action Unmark as favorite',
    actionCreateFreeTextTaskTitle: 'Action Create free text task',
    actionScanDocumentTitle: 'Action Scan document',
    actionScanForeignContractTitle: 'Action Scan foreign contract',
    otherActionIsRunning: 'Other action is running. Please wait until it is finished.',
    coverageUnknown: 'Copertura sconosciuta',
    uploadingDocuments: 'Uploading document(s)...'
};
